// Fantasy Life Hub — Draft pick options per category
// These populate the selection list during the draft.
// Categories with empty arrays use free-text "Custom..." input only.

export const PICK_OPTIONS = {
 nfl: [
  "ARI Cardinals", "ATL Falcons", "BAL Ravens", "BUF Bills",
  "CAR Panthers", "CHI Bears", "CIN Bengals", "CLE Browns",
  "DAL Cowboys", "DEN Broncos", "DET Lions", "GB Packers",
  "HOU Texans", "IND Colts", "JAX Jaguars", "KC Chiefs",
  "LV Raiders", "LAC Chargers", "LAR Rams", "MIA Dolphins",
  "MIN Vikings", "NE Patriots", "NO Saints", "NYG Giants",
  "NYJ Jets", "PHI Eagles", "PIT Steelers", "SF 49ers",
  "SEA Seahawks", "TB Buccaneers", "TEN Titans", "WAS Commanders",
 ],
 nba: [
  "ATL Hawks", "BOS Celtics", "BKN Nets", "CHA Hornets",
  "CHI Bulls", "CLE Cavaliers", "DAL Mavericks", "DEN Nuggets",
  "DET Pistons", "GS Warriors", "HOU Rockets", "IND Pacers",
  "LAC Clippers", "LAL Lakers", "MEM Grizzlies", "MIA Heat",
  "MIL Bucks", "MIN Timberwolves", "NO Pelicans", "NY Knicks",
  "OKC Thunder", "ORL Magic", "PHI 76ers", "PHX Suns",
  "POR Trail Blazers", "SAC Kings", "SA Spurs", "TOR Raptors",
  "UTA Jazz", "WAS Wizards",
 ],
 mlb: [
  "ARI D-backs", "ATL Braves", "BAL Orioles", "BOS Red Sox",
  "CHC Cubs", "CHW White Sox", "CIN Reds", "CLE Guardians",
  "COL Rockies", "DET Tigers", "HOU Astros", "KC Royals",
  "LAA Angels", "LAD Dodgers", "MIA Marlins", "MIL Brewers",
  "MIN Twins", "NYM Mets", "NYY Yankees", "OAK Athletics",
  "PHI Phillies", "PIT Pirates", "SD Padres", "SF Giants",
  "SEA Mariners", "STL Cardinals", "TB Rays", "TEX Rangers",
  "TOR Blue Jays", "WAS Nationals",
 ],
 nhl: [
  "ANA Ducks", "BOS Bruins", "BUF Sabres", "CGY Flames",
  "CAR Hurricanes", "CHI Blackhawks", "COL Avalanche",
  "CBJ Blue Jackets", "DAL Stars", "DET Red Wings", "EDM Oilers",
  "FLA Panthers", "LA Kings", "MIN Wild", "MTL Canadiens",
  "NSH Predators", "NJ Devils", "NYI Islanders", "NYR Rangers",
  "OTT Senators", "PHI Flyers", "PIT Penguins", "SJ Sharks",
  "SEA Kraken", "STL Blues", "TB Lightning", "TOR Maple Leafs",
  "VAN Canucks", "VGK Golden Knights", "WPG Jets", "WAS Capitals",
 ],
 ncaaf: [
  "Alabama", "Arizona State", "Auburn", "Baylor", "BYU",
  "Clemson", "Colorado", "Duke", "Florida", "Florida State",
  "Georgia", "Georgia Tech", "Indiana", "Iowa", "Iowa State",
  "Kansas", "Kansas State", "LSU", "Miami", "Michigan",
  "Michigan State", "Missouri", "NC State", "Nebraska",
  "North Carolina", "Notre Dame", "Ohio State", "Oklahoma",
  "Oklahoma State", "Ole Miss", "Oregon", "Penn State",
  "Pitt", "SC", "SMU", "Syracuse", "TCU", "Tennessee",
  "Texas", "Texas A&M", "Texas Tech", "UCLA", "USC",
  "Utah", "Virginia Tech", "Wake Forest", "Washington",
  "West Virginia", "Wisconsin",
  "Custom...",
 ],
 ncaab: [
  "Alabama", "Arizona", "Arkansas", "Auburn", "Baylor",
  "BYU", "Cincinnati", "Clemson", "Colorado", "Connecticut",
  "Creighton", "Dayton", "Duke", "Florida", "Gonzaga",
  "Houston", "Illinois", "Indiana", "Iowa State", "Kansas",
  "Kentucky", "Louisville", "LSU", "Marquette", "Maryland",
  "Memphis", "Miami", "Michigan", "Michigan State",
  "North Carolina", "Notre Dame", "Ohio State", "Oklahoma",
  "Oregon", "Penn State", "Purdue", "Saint Mary's",
  "San Diego State", "SC", "St. John's", "Syracuse", "TCU",
  "Tennessee", "Texas", "Texas A&M", "Texas Tech", "UCLA",
  "USC", "Villanova", "Virginia", "Wisconsin", "Xavier",
  "Custom...",
 ],
 tennis: [
  "Novak Djokovic", "Carlos Alcaraz", "Jannik Sinner",
  "Daniil Medvedev", "Alexander Zverev", "Andrey Rublev",
  "Holger Rune", "Casper Ruud", "Hubert Hurkacz", "Taylor Fritz",
  "Stefanos Tsitsipas", "Tommy Paul", "Frances Tiafoe",
  "Ben Shelton", "Felix Auger-Aliassime", "Alex de Minaur",
  "Grigor Dimitrov", "Lorenzo Musetti", "Ugo Humbert",
  "Sebastian Korda", "Arthur Fils",
  "Custom...",
 ],
 golf: [
  "Scottie Scheffler", "Xander Schauffele", "Rory McIlroy",
  "Jon Rahm", "Wyndham Clark", "Viktor Hovland",
  "Collin Morikawa", "Patrick Cantlay", "Ludvig Åberg",
  "Brian Harman", "Matt Fitzpatrick", "Max Homa",
  "Sahith Theegala", "Hideki Matsuyama", "Tommy Fleetwood",
  "Shane Lowry", "Tom Kim", "Sungjae Im", "Cameron Young",
  "Russell Henley",
  "Custom...",
 ],
 f1: [
  "Max Verstappen", "Lewis Hamilton", "Lando Norris",
  "Charles Leclerc", "Carlos Sainz", "Oscar Piastri",
  "George Russell", "Fernando Alonso", "Pierre Gasly",
  "Esteban Ocon", "Alex Albon", "Yuki Tsunoda",
  "Valtteri Bottas", "Daniel Ricciardo", "Zhou Guanyu",
  "Kevin Magnussen", "Nico Hulkenberg", "Lance Stroll",
  "Logan Sargeant", "Kimi Antonelli", "Liam Lawson",
  "Custom...",
 ],
 mls: [
  "Atlanta United", "Austin FC", "Charlotte FC", "Chicago Fire",
  "Cincinnati", "Colorado Rapids", "Columbus Crew", "D.C. United",
  "Dallas", "Houston Dynamo", "Inter Miami", "LA Galaxy", "LAFC",
  "Minnesota United", "Montreal", "Nashville SC", "New England",
  "NYCFC", "NY Red Bulls", "Orlando City", "Philadelphia Union",
  "Portland Timbers", "Real Salt Lake", "San Jose",
  "Seattle Sounders", "Sporting KC", "St. Louis CITY",
  "Toronto FC", "Vancouver",
  "Custom...",
 ],
 actor: ["Custom..."],
 actress: ["Custom..."],
 musician: ["Custom..."],
 country: ["Custom..."],
 stock: ["Custom..."],
};